functionsDirectory = "/home/ubuntu/aventura-alola/netlify/functions"
functionsDirectoryOrigin = "default"
redirectsOrigin = "config"
plugins = []
headers = []

[build]
publish = "/home/ubuntu/aventura-alola"
publishOrigin = "config"
commandOrigin = "config"
command = "echo 'Producción'"
functions = "/home/ubuntu/aventura-alola/netlify/functions"

[build.environment]

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]

[functions]

[functions."*"]

[[redirects]]
from = "/*"
to = "/index.html"
status = 200.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]