[build]
  command = "echo 'Aventura Alola - Listo para publicar'"
  publish = "."

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[context.production]
  command = "echo 'Producción'"

[context.deploy-preview]
  command = "echo 'Preview'"
